# Generated by Django 3.2.18 on 2023-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20230325_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
