# Generated by Django 3.2.18 on 2023-03-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20230330_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
    ]
