# Generated by Django 3.2.18 on 2023-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_reservation_number_of_guests'),
    ]

    operations = [
    ]
