# Generated by Django 3.2.18 on 2023-04-06 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2023, 12, 31)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
